### PR TITLE
Jupyter Notebook: Initial Version 

### PR DESCRIPTION
**Pull request by irahulsonkar**
Juypter notebook with widgets created for pure python HH model.

### CODE REVIEW

**Comment by pgleeson** [comment]
Thanks @irahulsonkar, looks good. A few minor suggestions for changes:
- [ ] When the HodgkinHuxley.py  is run as a standalong script, the window opened takes up the full screen and can't really be adjusted down due to the large text labels. I assume this was changed due to the plot being used in the notebook, but can you find a suitable middle ground (about 1/2 to 2/3 the current size in standalone). Maybe use the checks to see if it's being run as main?
- [ ] The "advanced input" option should be shown by default  as it's a key thing to adjust to get a feel for the model - the one pulse described should be all the cell gets. It probably doesn't require a new dedicated graph, as it's plot number 4 in the graphs below, but ensure the axes on the existing graph are dynamicaly adjusted
- [ ] It should be allowable to set the Na condutance to zero
- [ ] It would be nice to see whether the sliders are adjusted from their default values (i.e. if you only adjust one value, its value shows as red say, the rest are black)
- [ ] The range for amplitude can be -20 to 200 for a more physiological response range
- [ ]

**Comment by irahulsonkar** [comment]
Thanks for y

> Thanks @irahulsonkar, looks good. A few minor suggestions for changes:
> 
>     * [x]  When the HodgkinHuxley.py  is run as a standalong script, the window opened takes up the full screen and can't really be adjusted down due to the large text labels. I assume this was changed due to the plot being used in the notebook, but can you find a suitable middle ground (about 1/2 to 2/3 the current size in standalone). Maybe use the checks to see if it's being run as main?
> 
>     * [x]  The "advanced input" option should be shown by default  as it's a key thing to adjust to get a feel for the model - the one pulse described should be all the cell gets. It probably doesn't require a new dedicated graph, as it's plot number 4 in the graphs below, but ensure the axes on the existing graph are dynamicaly adjusted
> 
>     * [x]  It should be allowable to set the Na condutance to zero
> 
>     * [x]  It would be nice to see whether the sliders are adjusted from their default values (i.e. if you only adjust one value, its value shows as red say, the rest are black)
> 
>     * [x]  The range for amplitude can be -20 to 200 for a more physiological response range

Thank you for the suggestions @pgleeson. 
Latest commit include all the suggested changes.

**Comment by irahulsonkar** [comment]
Hi @pgleeson,
Please check the updated notebook and sphinx documentations as per last suggestions.

**Comment by irahulsonkar** [comment]
@pgleeson 
Thanks for the suggestions. 
Now, Sphinx documentation shows up properly with new python script. 
The default behavior for injection current in notebook changed to single pulse.  

P.S. The version number for the documentation can be changed from conf.py line 58-61. I kept it same as old '0.1', please update, if required.

**Pull request merged**
