### PR TITLE
ET notebook updated 

### PR DESCRIPTION
**Pull request by irahulsonkar**
NeuroML files can be updated through widgets and run with new parameter values within notebook.
- validate button on running shows files with valid/invalid sign for all the nml files.
- plot xlim ylim adjusted

### CODE REVIEW

**Comment by pgleeson** [comment]
@irahulsonkar Getting the following error:

Screenshot 2022-08-23 at 12 37 59

**Comment by irahulsonkar** [comment]
@pgleeson 
It could be the version issue if you are using the same Path and LEMS file as in tutorial directory and still getting the error. I checked on my local machine (python 3.7.6, IPython 7.34.0 & ipywidgets 7.7.1) and OSB workspace (python 3.9.7, IPython 7.29.0 & ipywidgets 7.7.1) before pull request and it worked fine. 

If you are using model other than HH then please share the LEMS file I will take a look.

**Comment by pgleeson** [comment]
Yes, I was using the unchanged paths for the lems file as included with it. 

It's nothing to do with the "Skipping file..." lines?

Can you maybe try checking out the repo to a fresh directory and try from tehre to ensure it's not picking up any previously generated (but not committed) files?

**Comment by irahulsonkar** [comment]
**Bug Fixed: moved set_title after setting content for tab widget.**

I tried on different machine (ubuntu with ipywidgets v8.0) then I got the same error. On my machine even in fresh directory it worked.
The problem was I created an empty tab widget with titles and then setup content so it was showing 'index of out of range'  while setting titles since no content exist. Now changed it to set_title only after content/children are set.

'Skipping files' is for those files which are in 'include' but not available in the specified project directory ('Path' in 1st cell). This is done to skip file like neurml definition, Cells.xml, Networks.xml, etc.

**Comment by irahulsonkar** [comment]
now commited under PR #36

**Pull request merged**
